image:
  repository: sowacr20260615.azurecr.io/sample-app
  tag: "c68458b"

replicaCount: 2
service:
  type: ClusterIP
  port: 80
  targetPort: 5000
ingress:
  enabled: false
autoscaling:
  enabled: false
