image:
  repository: sowacr20260615.azurecr.io/sample-app
  tag: latest

replicaCount: 2
service:
  type: ClusterIP
  port: 80
  targetPort: 5000
ingress:
  enabled: false
<<<<<<< HEAD

=======
>>>>>>> 6d66ab4 (Fix Helm chart values)
autoscaling:
  enabled: false
